spring:
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/data1?serverTimezone=UTC
    username: root
    password: 1105lwc
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
dynamic:
  datasource:
    ds1:
      url: jdbc:mysql://localhost:3306/data2?serverTimezone=UTC
      username: root
      password: 1105lwc
      driverClassName: com.mysql.cj.jdbc.Driver
    ds2:
      url: jdbc:mysql://localhost:3306/data3?serverTimezone=UTC
      username: root
      password: 1105lwc
      driverClassName: com.mysql.cj.jdbc.Driver